name: Update Data

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install libraries
        run: |
          pip install requests beautifulsoup4

      - name: Run spider
        run: python update.py

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "auto update data" || echo "no change"
          git push
